[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "vite"
  targetPort = 9500
  port = 8888
  functions = "netlify/functions"
  autoLaunch = true
